# Generated by Django 5.1.4 on 2024-12-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0002_imagemproduto_remove_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='descrição',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='logo',
            field=models.ImageField(default='', upload_to='logos'),
            preserve_default=False,
        ),
    ]
