# Generated by Django 5.1.4 on 2024-12-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0003_loja_descrição_loja_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
