# Generated by Django 5.1.4 on 2024-12-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0004_rename_descrição_loja_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
