# Generated by Django 5.1.4 on 2024-12-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0005_alter_loja_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/logos'),
        ),
    ]
