# Generated by Django 5.1.4 on 2024-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0006_alter_loja_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='email',
            field=models.EmailField(default='loja@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='endereco',
            field=models.CharField(default='rua dos bobocas, 354', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='telefone',
            field=models.CharField(default='16999999999', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loja',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos'),
        ),
    ]
