# Generated by Django 5.1.4 on 2024-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0009_alter_loja_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='logo',
            field=models.ImageField(max_length=255, null=True, upload_to='logos'),
        ),
    ]
